services:
  - type: web
    name: devops-demo
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn devopsDemo.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: devopsDemo.settings
      - key: PYTHON_VERSION
        value: 3.10
